// Mock data for SWAAD platform

export const chefs = [
  {
    id: 1,
    name: "Priya Sharma",
    kitchen: "Priya's Kitchen",
    avatar: "https://i.pravatar.cc/150?img=47",
    rating: 4.9,
    reviews: 245,
    experience: "7 years",
    location: "Lajpat Nagar, Delhi",
    distance: "1.2 km",
    cuisines: ["North Indian", "Punjabi", "Rajasthani"],
    isVeg: true,
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&q=80",
    price: 2500,
    meals: "Lunch + Dinner",
    specialty: "Dal Makhani & Butter Naan",
    verified: true,
    subscriptions: { weekly: 700, monthly: 2500, quarterly: 6500 },
    badge: "Top Rated",
  },
  {
    id: 2,
    name: "Sunita Devi",
    kitchen: "Sunita's Tiffin",
    avatar: "https://i.pravatar.cc/150?img=44",
    rating: 4.7,
    reviews: 189,
    experience: "5 years",
    location: "Karol Bagh, Delhi",
    distance: "2.3 km",
    cuisines: ["Gujarati", "Jain", "Rajasthani"],
    isVeg: true,
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80",
    price: 2200,
    meals: "Lunch only",
    specialty: "Gujarati Thali",
    verified: true,
    subscriptions: { weekly: 600, monthly: 2200, quarterly: 5800 },
    badge: "Jain Special",
  },
  {
    id: 3,
    name: "Lakshmi Iyer",
    kitchen: "South Spice Kitchen",
    avatar: "https://i.pravatar.cc/150?img=48",
    rating: 4.8,
    reviews: 312,
    experience: "10 years",
    location: "Saket, Delhi",
    distance: "3.1 km",
    cuisines: ["South Indian", "Tamil", "Kerala"],
    isVeg: false,
    image: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600&q=80",
    price: 2800,
    meals: "Breakfast + Lunch",
    specialty: "Idli Sambar & Chettinad Curry",
    verified: true,
    subscriptions: { weekly: 750, monthly: 2800, quarterly: 7200 },
    badge: "Most Popular",
  },
  {
    id: 4,
    name: "Anita Singh",
    kitchen: "Ghar Ka Zaika",
    avatar: "https://i.pravatar.cc/150?img=45",
    rating: 4.6,
    reviews: 156,
    experience: "4 years",
    location: "Rohini, Delhi",
    distance: "4.5 km",
    cuisines: ["UP Style", "North Indian", "Awadhi"],
    isVeg: false,
    image: "https://images.unsplash.com/photo-1505253304499-671c55fb57fe?w=600&q=80",
    price: 1999,
    meals: "Lunch + Dinner",
    specialty: "Lucknowi Biryani",
    verified: false,
    subscriptions: { weekly: 550, monthly: 1999, quarterly: 5200 },
    badge: "Budget Pick",
  },
  {
    id: 5,
    name: "Meena Joshi",
    kitchen: "Rajasthani Rasoi",
    avatar: "https://i.pravatar.cc/150?img=46",
    rating: 4.8,
    reviews: 203,
    experience: "8 years",
    location: "Dwarka, Delhi",
    distance: "5.2 km",
    cuisines: ["Rajasthani", "Marwari", "Jain"],
    isVeg: true,
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&q=80",
    price: 2300,
    meals: "Lunch + Dinner",
    specialty: "Dal Baati Churma",
    verified: true,
    subscriptions: { weekly: 650, monthly: 2300, quarterly: 6000 },
    badge: "New Chef",
  },
  {
    id: 6,
    name: "Rekha Mehta",
    kitchen: "Rekha's Home Food",
    avatar: "https://i.pravatar.cc/150?img=43",
    rating: 4.5,
    reviews: 98,
    experience: "3 years",
    location: "Noida Sector 18",
    distance: "6.8 km",
    cuisines: ["Punjabi", "North Indian"],
    isVeg: false,
    image: "https://images.unsplash.com/photo-1476224203421-9ac39bcb3df1?w=600&q=80",
    price: 2100,
    meals: "Dinner only",
    specialty: "Butter Chicken & Naan",
    verified: true,
    subscriptions: { weekly: 580, monthly: 2100, quarterly: 5500 },
    badge: "",
  },
];

export const weeklyMenu = {
  Monday: {
    breakfast: ["Poha", "Chai", "Banana"],
    lunch: ["Dal Tadka", "Aloo Gobi", "Rice", "Roti (4)"],
    dinner: ["Paneer Butter Masala", "Dal", "Rice", "Roti (4)", "Salad"],
  },
  Tuesday: {
    breakfast: ["Upma", "Chai", "Fruit"],
    lunch: ["Rajma", "Jeera Rice", "Roti (4)", "Raita"],
    dinner: ["Shahi Paneer", "Dal Makhani", "Naan (2)", "Rice", "Salad"],
  },
  Wednesday: {
    breakfast: ["Paratha (2)", "Curd", "Pickle"],
    lunch: ["Chole", "Puri (4)", "Aloo Sabzi", "Kheer"],
    dinner: ["Dal", "Mix Veg", "Rice", "Roti (4)", "Papad"],
  },
  Thursday: {
    breakfast: ["Idli (4)", "Sambar", "Chutney"],
    lunch: ["Kadhi Pakora", "Jeera Rice", "Roti (4)", "Salad"],
    dinner: ["Matar Paneer", "Dal", "Rice", "Roti (4)", "Salad"],
  },
  Friday: {
    breakfast: ["Poori Bhaji", "Chai"],
    lunch: ["Dal Palak", "Aloo Matar", "Rice", "Roti (4)", "Raita"],
    dinner: ["Paneer Tikka Masala", "Dal Fry", "Naan (2)", "Rice"],
  },
  Saturday: {
    breakfast: ["Chhole Bhature", "Chai"],
    lunch: ["Moong Dal", "Aloo Jeera", "Rice", "Roti (4)", "Papad"],
    dinner: ["Special Thali", "Dal", "Paneer", "Rice", "Roti (4)", "Dessert"],
  },
  Sunday: {
    breakfast: ["Puri (4)", "Halwa", "Chai"],
    lunch: ["Special Sunday Biryani", "Raita", "Salan", "Papad"],
    dinner: ["Light Khichdi", "Kadhi", "Rice", "Pickle", "Papad"],
  },
};

export const testimonials = [
  {
    id: 1,
    name: "Rahul Verma",
    avatar: "https://i.pravatar.cc/150?img=12",
    rating: 5,
    location: "Working Professional, Delhi",
    text: "SWAAD has literally changed my life. After moving from home, I was struggling with hostel food. Now I get fresh, healthy, ghar jaisa khana every day. Priya ji's tiffin feels exactly like mummy ke haath ka khana!",
    chef: "Priya's Kitchen",
  },
  {
    id: 2,
    name: "Anjali Kapoor",
    avatar: "https://i.pravatar.cc/150?img=32",
    rating: 5,
    location: "Software Engineer, Gurugram",
    text: "Finally found authentic Gujarati food in Delhi! Sunita ji's tiffin is perfectly portioned, always on time, and the taste is incredible. The Jain options are a huge bonus for our family. Highly recommend!",
    chef: "Sunita's Tiffin",
  },
  {
    id: 3,
    name: "Karthik Menon",
    avatar: "https://i.pravatar.cc/150?img=67",
    rating: 4,
    location: "Student, Saket",
    text: "Being a South Indian in Delhi, I always craved proper sambar and rasam. Lakshmi aunty's tiffin is a blessing! Affordable, tasty, and delivered right on time.",
    chef: "South Spice Kitchen",
  },
];

export const filters = [
  { id: "all", label: "All" },
  { id: "veg", label: "🟢 Veg Only" },
  { id: "non-veg", label: "🔴 Non-Veg" },
  { id: "under-2000", label: "Under ₹2000" },
  { id: "under-3000", label: "Under ₹3000" },
  { id: "top-rated", label: "⭐ Top Rated" },
  { id: "near-me", label: "📍 Near Me" },
  { id: "jain", label: "🌿 Jain Special" },
  { id: "south-indian", label: "South Indian" },
  { id: "north-indian", label: "North Indian" },
  { id: "gujarati", label: "Gujarati" },
];

export const howItWorks = [
  {
    step: 1,
    icon: "🔍",
    title: "Find Your Chef",
    desc: "Browse verified home chefs near you. Filter by cuisine, price, and ratings.",
  },
  {
    step: 2,
    icon: "📅",
    title: "Choose a Plan",
    desc: "Select weekly, monthly, or quarterly subscription. Customize meals to your preference.",
  },
  {
    step: 3,
    icon: "🍱",
    title: "Enjoy Fresh Food",
    desc: "Get freshly cooked tiffin delivered daily to your doorstep. Cancel anytime.",
  },
];

export const chefSubscribers = [
  { id: "EK", name: "Eleanor Kade", email: "eleanor.k@example.com", plan: "Monthly", startDate: "Oct 12, 2023", status: "Preparing" },
  { id: "MT", name: "Marcus Thorne", email: "m.thorne@web.com", plan: "Weekly", startDate: "Nov 02, 2023", status: "Out for Delivery" },
  { id: "SP", name: "Sarah Pendergast", email: "sarah.p@studio.io", plan: "Monthly", startDate: "Oct 28, 2023", status: "Scheduled" },
  { id: "JV", name: "Jameson Vane", email: "j.vane@creative.com", plan: "Weekly", startDate: "Dec 01, 2023", status: "Preparing" },
];

export const chefLedger = [
  { id: "TRX-9482", customer: "Sarah Miller", item: "Artisan Tiffin Bundle (Premium)", date: "Oct 18, 2023", status: "COMPLETED", amount: "+$84.00" },
  { id: "TRX-9475", customer: "James Low", item: "Weekly Meal Prep Subscription", date: "Oct 17, 2023", status: "COMPLETED", amount: "+$320.00" },
  { id: "TRX-9461", customer: "Elena Kovic", item: "Executive Chef Table Experience", date: "Oct 16, 2023", status: "PENDING", amount: "+$1,200.00" },
];
